import type { Metadata } from 'next';
import { ArrowUpRight } from 'lucide-react';
export const metadata: Metadata = { title: 'Our Founders | Finding Hope Africa' };
export default function FoundersPage(){return <main>
 <section className="page-hero founders-hero"><p className="eyebrow">About us</p><h1 className="script-heading">Our Founders</h1><p className="founders-hero-subtitle">Two people answered a call. Many others have helped hope grow.</p><p>Finding Hope Africa began in 2015 when Tatenda and Jerry Johnson opened a home in Harare to ten boys who had been living on the streets. What started as a place of safety has grown into work alongside children, young people, women, and families in Zimbabwe. Their story is one of faith, relationships, and the belief that every person has a God-given purpose.</p></section>
 <section className="founder-together"><div className="founder-photo-placeholder" role="img" aria-label="Photo of Tatenda and Jerry Johnson to be supplied"><span>Approved photo of Tatenda and Jerry to be supplied</span></div><p className="eyebrow">The beginning</p><h2>One open home.<br/>A growing community.</h2></section>
 <section className="founder-profiles">
  <article className="founder-profile"><div className="founder-portrait-placeholder" role="img" aria-label="Approved portrait of Tatenda Johnson to be supplied"><span>Tatenda portrait pending</span></div><div><p className="eyebrow">Co-founder</p><h2 className="script-heading">Meet Tatenda Johnson</h2><p>Tatenda leads FHA’s program strategy and community relationships in Zimbabwe. Her personal journey shaped a calling to walk with vulnerable children and families, not only through immediate challenges but toward education, belonging, and opportunity. She is the author of <em>Finding Hope</em>, a memoir published in 2025.</p></div></article>
  <article className="founder-profile founder-profile-reverse"><div className="founder-portrait-placeholder" role="img" aria-label="Approved portrait of Jerry Johnson to be supplied"><span>Jerry portrait pending</span></div><div><p className="eyebrow">Co-founder</p><h2 className="script-heading">Meet Jerry Johnson</h2><p>Jerry supports FHA’s fundraising and operations in the United States, helping connect supporters with the work taking place in Zimbabwe. He has helped build a community around the mission, including through the annual Walk for Hope fundraiser in California. Together with Tatenda, he remains committed to the relationships at the heart of FHA.</p></div></article>
 </section>
 <section className="founder-conversation"><div><p className="eyebrow">A conversation with our founders</p><h2 className="script-heading">Why we began.<br/>What we have learned.<br/>Where we hope to go.</h2></div><div className="media-placeholder" role="img" aria-label="Tatenda and Jerry Q and A video will be added when supplied"><span className="media-placeholder-label">Founder conversation</span><strong>Video coming soon</strong><span>FHA will provide the approved Q&amp;A video.</span></div></section>
 <section className="founder-legacy"><p className="eyebrow">The work continues through people</p><h2 className="script-heading">Hope grows together.</h2><p>Finding Hope Africa is more than its founders. Local staff, facilitators, partners, and community leaders carry the work forward every day. Tatenda and Jerry’s hope is to keep equipping people who can care for their neighbours, share their gifts, and strengthen the communities they know best.</p></section>
 <section className="founder-cta"><div><p className="eyebrow light">Be part of the story</p><h2 className="script-heading">Carry hope forward.</h2><p>Your support helps FHA keep walking alongside children, young people, and families while investing in local people who can carry that care forward.</p></div><div className="founder-cta-links"><a className="button button-light" href="/donate">Support us <ArrowUpRight size={17}/></a><a className="button button-light" href="/impact">Our impact <ArrowUpRight size={17}/></a><a className="button button-light" href="/programs">Our programmes <ArrowUpRight size={17}/></a></div></section>
 </main>}
