import type { Metadata } from 'next';
import { ArrowUpRight } from 'lucide-react';
import { MinistryTimeline } from '../../components/ministry-timeline';
export const metadata: Metadata = { title: 'Our Story | Finding Hope Africa' };
export default function AboutPage() { return <main>
  <section className="page-hero about-hero"><p className="eyebrow">About us</p><h1 className="script-heading">Our Story</h1><h2 className="about-page-title">The story that started it all</h2><p>In 2015, Tatenda and Jerry Johnson opened a home in Harare to ten boys who had been living on the streets. It was a place of safety and belonging, and the beginning of Finding Hope Africa. As they got to know the boys and their families, the Johnsons saw that lasting change would take more than a roof: it would take relationships, education, practical support, faith, and people willing to walk alongside them.</p></section>
  <section className="page-story about-origin"><div className="story-photo" role="img" aria-label="Children learning together"/><div className="page-copy"><p>Tatenda’s own journey helped shape that calling. After losing her mother when she was young, she knew something of grief and uncertainty. Her story, later told in her 2025 memoir <em>Finding Hope</em>, became part of the reason she chose to stand with children and families who felt forgotten.</p><p>What began with one home has grown into work across education, shelter, livelihoods, healthcare access, and creative arts. Through it all, FHA has held on to one simple conviction: every person has dignity, gifts, and a God-given purpose worth nurturing.</p><a className="button button-dark" href="/founders">Meet our founders <ArrowUpRight size={17}/></a></div></section>
  <section className="about-timeline"><div className="about-timeline-heading"><p className="eyebrow">Our journey</p><h2 className="script-heading">Our journey</h2><p>Walking together since 2015.</p></div><MinistryTimeline/></section>
  <section className="future-story"><div className="future-story-copy"><p className="eyebrow">Where the story is leading</p><h2 className="script-heading">Where the story is leading</h2><p className="future-story-subtitle">Equipping the church. Raising up people of purpose.</p><p>Our existing commitments to children, young people, and families continue. At the same time, we are working toward a future in which local churches have more people ready to share the gospel, lead with care, and serve their communities.</p><p>We want to invest in local leaders and create space for people to discover their calling and use their gifts. FHA cannot, and should not, do everything itself. Our hope is that the work of reaching and caring for people will continue through the churches and communities that know them best. We listen first, respond within our capacity, and never make practical support conditional on religious participation.</p></div><div className="media-placeholder" role="img" aria-label="Tatenda interview video will be added when supplied"><span className="media-placeholder-label">Tatenda interview</span><strong>Video coming soon</strong><span>FHA will provide the approved video.</span></div></section>
  <section className="memoir-section"><div className="memoir-cover" aria-label="Official Finding Hope book cover to be supplied"><span>Finding Hope</span><small>Tatenda Johnson · Memoir · 2025</small><small className="asset-pending">Official cover image pending</small></div><div><p className="eyebrow">The story behind Finding Hope</p><h2 className="script-heading">A story of hope through loss</h2><p>Tatenda shares more of the journey that shaped this work in her memoir <em>Finding Hope</em>, published in 2025. Her story is a reminder that hope can grow even through loss, and that one person’s calling can open a door for many others.</p><button className="button button-dark" type="button" disabled aria-describedby="purchase-note">Purchase the book <ArrowUpRight size={17}/></button><p className="asset-note" id="purchase-note">The purchase button will be linked when FHA confirms the destination.</p></div></section>
  <section className="page-links"><a href="/impact"><span>01</span><strong>Our Impact</strong><ArrowUpRight/></a><a href="/programs"><span>02</span><strong>Our Programmes</strong><ArrowUpRight/></a></section>
 </main>; }
