'use client';
import { ArrowUpRight, Play } from 'lucide-react';
const stories = [
  { title:'A place to learn, grow and belong', tag:'Education', image:'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=900&q=85' },
  { title:'Building futures with practical skills', tag:'Livelihoods', image:'https://images.unsplash.com/photo-1529390079861-591de354faf5?auto=format&fit=crop&w=900&q=85' },
  { title:'When a home becomes a family', tag:'Ruwa Home', image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?auto=format&fit=crop&w=900&q=85' },
];
export default function Home(){
 return <main>
  <section id="top" className="hero"><div className="hero-image"/><div className="hero-overlay"/><div className="hero-content"><p className="eyebrow light">Zimbabwe · Since 2015</p><h1>Rescue.<br/><em>Rebuild.</em><br/>Reintegrate.</h1><p className="hero-copy">We walk with Zimbabwe’s orphaned, poor and vulnerable children and families until each one finds hope and a purpose.</p><a className="button button-light" href="#impact">Our impact <ArrowUpRight size={17}/></a></div><div className="hero-note">One life at a time <span>↓</span></div></section>
  <section id="impact" className="impact-band"><div className="impact-intro"><p className="eyebrow">Our impact</p><h2>Finding Hope<br/><span>Together</span></h2><a className="text-link light-link" href="/impact">See our story <ArrowUpRight size={17}/></a></div><div className="stats"><div><strong>9</strong><span>programmes</span></div><div><strong>11</strong><span>years of service</span></div><div><strong>100s</strong><span>of lives changed</span></div><div><strong>1</strong><span>shared purpose</span></div></div></section>
  <section className="video-section"><div className="section-label"><span className="eyebrow">See hope in motion</span><span className="line"/></div><div className="video-placeholder"><div className="video-image"/><div className="video-tint"/><button className="play-button" aria-label="Play video"><Play fill="currentColor" size={24}/></button><span className="video-caption">A glimpse into Finding Hope Africa</span></div></section>
  <section id="story" className="story-section"><div className="story-photo"/><div className="story-copy"><p className="eyebrow">Our story</p><h2>Hope is a place<br/>we build <em>together.</em></h2><p>Finding Hope Africa began in 2015 when Tatenda and Jerry Johnson opened their home in Harare to ten boys living on the streets. That one act of rescue has grown into a family of programmes — education, shelter, healthcare, livelihoods training and the creative arts — walking with Zimbabwe’s most vulnerable children, youth and mothers from crisis to a life of purpose.</p><a className="button button-dark" href="/about">Read more <ArrowUpRight size={17}/></a></div></section>
  <section id="stories" className="stories-section"><div className="section-heading"><div><p className="eyebrow">From the blog</p><h2>Stories of <em>life change.</em></h2></div><a className="text-link" href="/blog">Read all stories <ArrowUpRight size={17}/></a></div><div className="story-grid">{stories.map(s=><article className="story-card" key={s.title}><div className="card-image" style={{backgroundImage:`url(${s.image})`}}/><div className="card-body"><span>{s.tag}</span><h3>{s.title}</h3><a href="/blog">Read story <ArrowUpRight size={15}/></a></div></article>)}</div></section>
  <section id="donate" className="donate-cta"><div><p className="eyebrow light">Get involved</p><h2>There is room<br/>for you <em>here.</em></h2></div><a className="button button-light" href="/donate">Give today <ArrowUpRight size={17}/></a></section>
 </main>;
}
